[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0284c7"
backgroundColor = "#0b1120"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"
